version: "3"

services:
  api:
    image: git.kodix.dev/buildkit/golang:latest
    command: sleep infinity
    volumes:
      - ..:/usr/src/hr:cached
    ports:
      - "8080:8080"
    networks:
      hr:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5432
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - hr
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

volumes:
  postgres:

networks:
  hr:
